export class TestConst {
  public static readonly UT_TAG = "QCloudTest";
  public static readonly STS_CREDENTIAL_URL = "http://x.x.x.x:3000/sts";
  public static readonly SIGN_URL = "http://x.x.x.x:3000/sts-direct-sign";
  public static readonly SECRET_ID = "";
  public static readonly SECRET_KEY = "";
  public static readonly PERSIST_BUCKET_REGION = "ap-guangzhou";
  public static readonly PERSIST_BUCKET = "mobile-ut-1253960454";

  public static readonly PERSIST_BUCKET_BIG_FILE_PATH = "do_not_remove/522m.zip";
  public static readonly PERSIST_BUCKET_BIG_10M_PATH = "do_not_remove/big_object";
  public static readonly PERSIST_BUCKET_PIC_PATH = "do_not_remove/image.png";
  public static readonly PERSIST_BUCKET_PIC_CI_PATH = "do_not_remove/image_ci.png";
  public static readonly PERSIST_BUCKET_PIC_CI_JPG_PATH = "do_not_remove/image_ci.jpg";
  public static readonly PERSIST_BUCKET_PIC_CI_ROTATE_PATH = "do_not_remove/image_ci_rotate.jpg";
  public static readonly PERSIST_BUCKET_PIC_6M_PATH = "do_not_remove/6m.jpg";
  public static readonly PERSIST_BUCKET_QR_PATH = "do_not_remove/qr.png";
  public static readonly PERSIST_BUCKET_VIDEO_PATH = "do_not_remove/video.mp4";
  public static readonly PERSIST_BUCKET_PUT_PATH = "do_not_remove/putTest.txt";
}
