// /**
//  * 网络端 鸿蒙执行代理实现
//  */
// import { HttpRequest } from './HttpRequest';
// import { NetworkProxy } from './NetworkProxy';
// import http from '@ohos.net.http';
// import { HttpResult } from './HttpResult';
// import { taskpool } from '@kit.ArkTS';
// import { QCloudEventType } from '../task/base/QCloudTask';
// import { QCloudTransferData } from '../task/base/QCloudTransferData';
// import { QCloudRequestData } from '../task/http/QCloudRequestData';
// import { HttpProgress } from './HttpProgress';
// import { QCloudLogger } from '../logger/QCloudLogger';
//
// export class HarmonyProxy extends NetworkProxy {
//   executeHttpRequest(qcloudRequestData: QCloudRequestData) {
//     let httpRequest = http.createHttp();
//
//   }
// }