// import { HttpRequest } from './HttpRequest';
// import { HttpResult } from './HttpResult';
// import http from '@ohos.net.http';
// import { QCloudRequestData } from '../task/http/QCloudRequestData';
//
// /**
//  * 网络端 执行代理
//  */
// export abstract class NetworkProxy {
//   abstract executeHttpRequest(qcloudRequestData: QCloudRequestData);
//   // abstract convertResponse(httpRequest: HttpRequest<T>, response: http.HttpResponse): HttpResult<T>;
//   // abstract cancel();
// }